language: python
python:
  - 3.6
sudo: required
install: pip install -r requirements.txt
script: nosetests app.py
deploy:
  provider: heroku
  api_key:
    secure: "Dz2Y2GwXm62bZ5KnmY/ydKvgDr1rchXhwWJy4tExfWi+XU0/y99QpQJwybyboogGliiPw8/Rp4y5Qmx099me//WdqJeP38zPo69Iye4YSC2FTyOfVuBTEFZg9CCZZ5sIYibKR1rnOb1300JOgi21Co4vA8BneTtPBTUi4u6RJua/fTdZIpjfJx0Z4Zr5O30Ck3oDJg5hRAZra6WOBVqXDy6N4e6AmD7+3BvX+VE8vMEcfqcJeRCoYXqWzchngbv3u1pProSMPI1YHWuF8SSS6jj018eIPnaOBSlKPMW60adipCMbdOIaWRt7k67rTskpsIULYl9nRrwYfzlnOzqTpaCeFIQDKNNImNMfBwaRvGAb4ex4BydKQsGAVt2RLkpLqYi1yoBv6fn+FGH0cwHWDqrMZalwGWQShG2r0pJbZQ/Nd22K1QEpg5XlQq7gKPoGVYfXDZk+aZukc+BVtf6rekPQh+b0FJovoUwoLBJjgjvDYKc3wAKGeBgj2KgtnIzQs/++PnW7M21m9ueqlgmW41f7OhHQUbGzDdRQqbxcG79uoSST4Nzf1XsgiCyPmXhjOaffLw1LTguybn9kQB/QQeBElq4OYmNjmKOxCS6bBHC/E5FznGM0bwJ7ATs8tNxoS0Y81IL69iU547r2HsiNaUIftpdWUMap1QDQ3SmUg3o="
  app: meilix-generator
  on:
    repo: fossasia/meilix-generator
